services:
  app:
    build:
      context: .
      dockerfile: ../src/Dockerfile
    working_dir: /workspace
    volumes:
      - ..:/workspace:cached
    ports:
      - 3000:3000
    depends_on:
      - vllm

  # vllm: Faster inference (optimized batching) and support for larger models, but more complex setup and higher resource usage.
  vllm:
    image: vllm/vllm-openai:latest
    ports:
      - 8000:8000
    environment:
      - MODEL_NAME=microsoft/phi-2
    command: --model microsoft/phi-2 --tensor-parallel-size 1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - huggingface_cache:/root/.cache/huggingface

  # test:
  #   image: nvidia/cuda:12.9.0-base-ubuntu22.04
  #   command: nvidia-smi
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]
